import Link from 'next/link';
import { ArrowRight, Bot, BriefcaseBusiness, CheckCircle2, FileUp, ShieldCheck, Sparkles, UserRound } from 'lucide-react';
export const metadata={title:'Supersonic Fast Cash | File Your Taxes or Run Your Tax Office',description:'Guided self-file tax preparation and professional tax-office software with document import, PARIS interview assistance, review workflows, and e-file architecture.'};
const selfFile=['Guided step-by-step tax interview','Upload W-2 and supported 1099 documents','Review imported values before they enter the return','Plain-language explanations and progress tracking','Return review before electronic filing'];
const pro=['Tax office and preparer management','Client intake and document workflow','W-2, 1099, Schedule C and deduction workflows','Review, rejection and acknowledgment tracking','IRS MeF and approved bank-product integration architecture'];
export default function TaxSoftwarePage(){return <main className="min-h-screen bg-white text-slate-950">
<section className="overflow-hidden bg-gradient-to-b from-sky-50 to-white"><div className="mx-auto max-w-7xl px-6 py-20 lg:grid lg:grid-cols-2 lg:items-center lg:gap-14 lg:px-8 lg:py-28">
<div><div className="inline-flex items-center gap-2 rounded-full border border-sky-200 bg-white px-4 py-2 text-sm font-semibold text-sky-900"><Sparkles className="h-4 w-4"/> Supersonic Fast Cash Tax Software</div><h1 className="mt-6 text-4xl font-bold tracking-tight sm:text-6xl">Taxes, guided from start to finish.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">File your own return with a guided interview or use the professional workspace to prepare returns for clients. Upload tax documents, answer simple questions, review the return, and move through one clear workflow.</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/tax-software/self-file" className="inline-flex items-center gap-2 rounded-xl bg-sky-700 px-6 py-3.5 font-semibold text-white">Start self-file <ArrowRight className="h-4 w-4"/></Link><Link href="/tax-software/professional" className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-6 py-3.5 font-semibold">Professional software <BriefcaseBusiness className="h-4 w-4"/></Link></div><p className="mt-4 text-sm text-slate-500">You review your information before filing. External e-file and bank products require applicable provider approval and production credentials.</p></div>
<div className="mt-12 rounded-3xl border border-slate-200 bg-white p-6 shadow-xl lg:mt-0"><div className="flex items-center justify-between border-b border-slate-100 pb-4"><div><p className="text-sm text-slate-500">Guided return</p><p className="font-bold">Your 2026 Federal Return</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-sm font-semibold text-emerald-800">Interview</span></div><div className="py-6"><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-2/5 rounded-full bg-sky-600"/></div><p className="mt-3 text-sm text-slate-500">Income · Step 4 of 10</p><div className="mt-6 rounded-2xl bg-slate-50 p-5"><div className="flex gap-3"><Bot className="mt-1 h-6 w-6 text-sky-700"/><div><p className="font-bold">PARIS</p><p className="mt-1 text-slate-700">Let’s add your income. Do you have a W-2 from an employer?</p></div></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl border bg-white p-3 text-center font-semibold">Yes</div><div className="rounded-xl border bg-white p-3 text-center font-semibold">No</div></div><div className="mt-3 rounded-xl border border-dashed border-slate-300 bg-white p-4 text-center"><FileUp className="mx-auto h-5 w-5"/><p className="mt-2 font-semibold">Upload or photograph W-2</p><p className="text-xs text-slate-500">Imported fields must be reviewed before use.</p></div></div></div></div>
</div></section>
<section className="mx-auto max-w-7xl px-6 py-16 lg:px-8"><div className="grid gap-6 lg:grid-cols-2"><article className="rounded-3xl border border-slate-200 p-8"><UserRound className="h-8 w-8 text-sky-700"/><p className="mt-5 text-sm font-bold uppercase tracking-wider text-sky-700">For individuals</p><h2 className="mt-2 text-3xl font-bold">Prepare your own taxes</h2><p className="mt-3 text-slate-600">PARIS guides the interview, explains questions, helps organize imported tax documents, and builds the return workflow for your review.</p><div className="mt-7 space-y-3">{selfFile.map(x=><div key={x} className="flex gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 text-emerald-600"/><span>{x}</span></div>)}</div><Link href="/tax-software/self-file" className="mt-8 inline-flex items-center gap-2 font-bold text-sky-800">Explore self-file <ArrowRight className="h-4 w-4"/></Link></article>
<article className="rounded-3xl bg-slate-950 p-8 text-white"><BriefcaseBusiness className="h-8 w-8 text-sky-300"/><p className="mt-5 text-sm font-bold uppercase tracking-wider text-sky-300">For tax professionals</p><h2 className="mt-2 text-3xl font-bold">Run your tax office</h2><p className="mt-3 text-slate-300">A professional workspace for preparers, EROs and multi-office operations with controlled access and auditable return workflows.</p><div className="mt-7 space-y-3">{pro.map(x=><div key={x} className="flex gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 text-emerald-300"/><span>{x}</span></div>)}</div><Link href="/tax-software/professional" className="mt-8 inline-flex items-center gap-2 font-bold text-sky-300">Explore professional software <ArrowRight className="h-4 w-4"/></Link></article></div></section>
<section className="border-t bg-slate-50"><div className="mx-auto max-w-7xl px-6 py-12 lg:px-8"><div className="flex gap-4"><ShieldCheck className="h-7 w-7"/><div><h2 className="text-xl font-bold">Review before filing</h2><p className="mt-2 max-w-3xl text-slate-600">Document extraction and PARIS assistance accelerate data entry, but imported values, taxpayer answers, elections, signatures and the final return remain reviewable before electronic submission.</p></div></div></div></section></main>}
