'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowRight,BadgeCheck,Bot,Building2,CheckCircle2,FileText,Landmark,ShieldCheck,WalletCards} from 'lucide-react';
const steps=['Taxpayer intake','PARIS interview','W-2 import & confirmation','Return preparation','Diagnostics & review','Bank product selection','Consent & application','Provider response'];
export default function SoftwareDemo(){const [step,setStep]=useState(0);return <main className="min-h-screen bg-slate-50 text-slate-950"><div className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><div><p className="text-sm font-semibold text-sky-700">Supersonic Fast Cash</p><h1 className="text-xl font-bold">Software Provider Demonstration</h1></div><span className="rounded-full bg-amber-50 px-3 py-1 text-sm font-semibold text-amber-900">Synthetic demo data</span></div></div><div className="mx-auto max-w-7xl px-6 py-10"><div className="grid gap-6 lg:grid-cols-[260px_1fr]"><aside className="rounded-2xl border bg-white p-4"><p className="px-2 text-xs font-bold uppercase tracking-wider text-slate-400">End-to-end workflow</p><div className="mt-3 space-y-1">{steps.map((s,i)=><button key={s} onClick={()=>setStep(i)} className={`w-full rounded-lg px-3 py-2 text-left text-sm font-medium ${i===step?'bg-sky-50 text-sky-900':'hover:bg-slate-50'}`}><span className="mr-2">{i<step?'✓':i+1}</span>{s}</button>)}</div></aside><section className="space-y-6"><div className="rounded-3xl bg-slate-950 p-8 text-white"><p className="text-sm font-bold uppercase tracking-wider text-sky-300">Step {step+1} of {steps.length}</p><h2 className="mt-2 text-3xl font-bold">{steps[step]}</h2><p className="mt-4 max-w-3xl text-slate-300">{[
'Create or locate the taxpayer record and start the tax-year return.',
'PARIS conducts a guided interview covering household, income, deductions, credits and missing information.',
'Upload a W-2 or supported 1099. OCR extracts values and the taxpayer or preparer confirms them before they enter the return.',
'Confirmed source data feeds the deterministic TY2026 return calculation and activates applicable forms and schedules.',
'The diagnostics engine identifies incomplete taxpayer data, unconfirmed documents, missing authorizations and other filing issues.',
'When a refund is expected, the taxpayer can choose an available refund-transfer or advance product.',
'The software records the product selection, required consent version, application status and originating office/preparer.',
'Provider acknowledgments, decisions, funding and reconciliation statuses return to the tax-office workflow.'
][step]}</p><div className="mt-7 flex flex-wrap gap-3">{step>0&&<button onClick={()=>setStep(step-1)} className="rounded-lg border border-white/20 px-4 py-2 font-semibold">Previous</button>}{step<steps.length-1&&<button onClick={()=>setStep(step+1)} className="inline-flex items-center gap-2 rounded-lg bg-white px-4 py-2 font-semibold text-slate-950">Continue <ArrowRight className="h-4 w-4"/></button>}</div></div><div className="grid gap-4 md:grid-cols-4">{[[Bot,'PARIS','Guided interview'],[FileText,'Tax Engine','Forms & calculations'],[WalletCards,'Bank Products','Application workflow'],[ShieldCheck,'Security','RLS & audit trail']].map(([I,t,d]:any)=><div key={t} className="rounded-2xl border bg-white p-5"><I className="h-6 w-6 text-sky-700"/><p className="mt-4 font-bold">{t}</p><p className="mt-1 text-sm text-slate-500">{d}</p></div>)}</div><div className="rounded-2xl border bg-white p-6"><div className="flex items-center gap-3"><Landmark className="h-6 w-6"/><div><h3 className="font-bold">EPS integration point</h3><p className="text-sm text-slate-500">Supersonic already models the bank-product application and lifecycle. EPS's certified transport/file/API adapter will be implemented against the technical specification EPS releases after software review.</p></div></div></div><div className="flex flex-wrap gap-3"><Link href="/tax-software/self-file" className="rounded-xl bg-sky-700 px-5 py-3 font-bold text-white">Open self-file</Link><Link href="/tax-software/self-file/return" className="rounded-xl border bg-white px-5 py-3 font-bold">Open return workspace</Link><Link href="/tax-software/professional" className="rounded-xl border bg-white px-5 py-3 font-bold">Professional edition</Link></div></section></div></div></main>}
