import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '@/lib/supabase/server';
import {applyRateLimit} from '@/lib/api/withRateLimit';
import {calculateBase1040_2026,type FilingStatus} from '@/lib/tax-software/calculation/ty2026-base-1040';
export async function POST(req:NextRequest){const limited=await applyRateLimit(req,'api');if(limited)return limited;const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});const {returnId}=await req.json();if(!returnId)return NextResponse.json({error:'returnId is required'},{status:400});
const {data:r}=await supabase.from('tax_returns').select('id,user_id,filing_status,tax_year').eq('id',returnId).eq('user_id',user.id).maybeSingle();if(!r)return NextResponse.json({error:'Return not found'},{status:404});if(Number(r.tax_year)!==2026)return NextResponse.json({error:'This calculation engine is for tax year 2026'},{status:400});
const [{data:w2},{data:i1099},{data:sc},{data:itemized}]=await Promise.all([supabase.from('tax_w2_income').select('wages,federal_withholding').eq('tax_return_id',returnId),supabase.from('tax_1099_income').select('form_type,amount,federal_withholding').eq('tax_return_id',returnId),supabase.from('tax_schedule_c').select('net_profit').eq('tax_return_id',returnId),supabase.from('tax_itemized_deductions').select('total_itemized').eq('tax_return_id',returnId).maybeSingle()]);
const wages=(w2||[]).reduce((s,x)=>s+Number(x.wages||0),0);const withholding=(w2||[]).reduce((s,x)=>s+Number(x.federal_withholding||0),0)+(i1099||[]).reduce((s,x)=>s+Number(x.federal_withholding||0),0);const interest=(i1099||[]).filter(x=>x.form_type==='INT').reduce((s,x)=>s+Number(x.amount||0),0);const dividends=(i1099||[]).filter(x=>x.form_type==='DIV').reduce((s,x)=>s+Number(x.amount||0),0);const other=(i1099||[]).filter(x=>!['INT','DIV','NEC'].includes(x.form_type)).reduce((s,x)=>s+Number(x.amount||0),0);const business=(sc||[]).reduce((s,x)=>s+Number(x.net_profit||0),0)+(i1099||[]).filter(x=>x.form_type==='NEC').reduce((s,x)=>s+Number(x.amount||0),0);
const result=calculateBase1040_2026({filingStatus:r.filing_status as FilingStatus,wages,interest,dividends,businessIncome:business,otherIncome:other,itemizedDeductions:Number(itemized?.total_itemized||0),federalWithholding:withholding});
await supabase.from('tax_calculations').insert({return_id:returnId,tax_year:2026,filing_status:r.filing_status,total_income:result.totalIncome,adjusted_gross_income:result.adjustedGrossIncome,taxable_income:result.taxableIncome,federal_tax:result.incomeTax,total_tax:result.totalTax,federal_withholding:withholding,estimated_refund:result.refundAmount,amount_owed:result.amountOwed,calculation_data:result,calculation_version:'ty2026-base-1040-v1'});
await supabase.from('tax_returns').update({total_income:result.totalIncome,adjusted_gross_income:result.adjustedGrossIncome,taxable_income:result.taxableIncome,total_tax:result.totalTax,total_payments:result.totalPayments,refund_amount:result.refundAmount,amount_owed:result.amountOwed,updated_at:new Date().toISOString()}).eq('id',returnId).eq('user_id',user.id);
return NextResponse.json({success:true,result});}
