import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '@/lib/supabase/server';
import {applyRateLimit} from '@/lib/api/withRateLimit';
import {calculateBase1040_2026,STANDARD_DEDUCTION_2026,type FilingStatus} from '@/lib/tax-software/calculation/ty2026-base-1040';
export async function POST(req:NextRequest){const limited=await applyRateLimit(req,'api');if(limited)return limited;const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});const body=await req.json().catch(()=>null);const returnId=body?.returnId;if(typeof returnId!=='string'||!returnId.trim())return NextResponse.json({error:'returnId is required'},{status:400});
const {data:r,error:returnError}=await supabase.from('tax_returns').select('id,created_by_user_id,filing_status,tax_year,return_json').eq('id',returnId).eq('created_by_user_id',user.id).eq('service_type','self_file').maybeSingle();if(returnError)return NextResponse.json({error:'Unable to load tax return'},{status:500});if(!r)return NextResponse.json({error:'Return not found'},{status:404});if(Number(r.tax_year)!==2026)return NextResponse.json({error:'This calculation engine is for tax year 2026'},{status:400});
if(!Object.prototype.hasOwnProperty.call(STANDARD_DEDUCTION_2026,r.filing_status))return NextResponse.json({error:'Select a supported filing status before calculating'},{status:400});
const sources=await Promise.all([supabase.from('tax_w2_income').select('wages,federal_withholding').eq('tax_return_id',returnId),supabase.from('tax_1099_income').select('form_type,amount,federal_withholding').eq('tax_return_id',returnId),supabase.from('tax_schedule_c').select('net_profit').eq('tax_return_id',returnId),supabase.from('tax_itemized_deductions').select('total_itemized').eq('tax_return_id',returnId).maybeSingle()]);
if(sources.some(source=>source.error))return NextResponse.json({error:'Unable to load all calculation inputs'},{status:500});
const [{data:w2},{data:i1099},{data:sc},{data:itemized}]=sources;
const wages=(w2||[]).reduce((s,x)=>s+Number(x.wages||0),0);const withholding=(w2||[]).reduce((s,x)=>s+Number(x.federal_withholding||0),0)+(i1099||[]).reduce((s,x)=>s+Number(x.federal_withholding||0),0);const interest=(i1099||[]).filter(x=>x.form_type==='INT').reduce((s,x)=>s+Number(x.amount||0),0);const dividends=(i1099||[]).filter(x=>x.form_type==='DIV').reduce((s,x)=>s+Number(x.amount||0),0);const other=(i1099||[]).filter(x=>!['INT','DIV','NEC'].includes(x.form_type)).reduce((s,x)=>s+Number(x.amount||0),0);const business=(sc||[]).reduce((s,x)=>s+Number(x.net_profit||0),0)+(i1099||[]).filter(x=>x.form_type==='NEC').reduce((s,x)=>s+Number(x.amount||0),0);
const result=calculateBase1040_2026({filingStatus:r.filing_status as FilingStatus,wages,interest,dividends,businessIncome:business,otherIncome:other,itemizedDeductions:Number(itemized?.total_itemized||0),federalWithholding:withholding});
const {error:calculationError}=await supabase.from('tax_calculations').insert({user_id:user.id,tax_year:2026,filing_status:r.filing_status,total_income:result.totalIncome,adjusted_gross_income:result.adjustedGrossIncome,taxable_income:result.taxableIncome,federal_tax:result.incomeTax,total_tax:result.totalTax,federal_withholding:withholding,estimated_refund:result.refundAmount,is_refund:result.refundAmount>0,calculation_data:{...result,returnId,calculationVersion:'ty2026-base-1040-v1'}});
if(calculationError)return NextResponse.json({error:'Unable to save calculation'},{status:500});
const {data:savedReturn,error:saveError}=await supabase.from('tax_returns').update({total_income:result.totalIncome,adjusted_gross_income:result.adjustedGrossIncome,taxable_income:result.taxableIncome,federal_tax:result.incomeTax,federal_refund:result.refundAmount,return_json:{...r.return_json,calculation:{...result,calculationVersion:'ty2026-base-1040-v1'}},updated_at:new Date().toISOString()}).eq('id',returnId).eq('created_by_user_id',user.id).eq('service_type','self_file').select('id').maybeSingle();
if(saveError||!savedReturn)return NextResponse.json({error:'Unable to save calculated return'},{status:500});
return NextResponse.json({success:true,result});}
