'use client';
import {useEffect,useState,Suspense} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
type W2={employerEin:string;employerName:string;wages:string;federalWithholding:string;socialSecurityWages:string;socialSecurityTax:string;medicareWages:string;medicareTax:string;stateCode:string;stateWages:string;stateWithholding:string};
const keys:[keyof W2,string][]=[['employerEin','Employer EIN'],['employerName','Employer name'],['wages','Box 1 wages'],['federalWithholding','Box 2 federal withholding'],['socialSecurityWages','Box 3 Social Security wages'],['socialSecurityTax','Box 4 Social Security tax'],['medicareWages','Box 5 Medicare wages'],['medicareTax','Box 6 Medicare tax'],['stateCode','Box 15 state'],['stateWages','Box 16 state wages'],['stateWithholding','Box 17 state withholding']];
function W2ConfirmContent(){const router=useRouter();const params=useSearchParams();const [values,setValues]=useState<W2>(Object.fromEntries(keys.map(([k])=>[k,''])) as unknown as W2);const [agreed,setAgreed]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [fileName,setFileName]=useState('');
useEffect(()=>{try{const raw=sessionStorage.getItem('sfc:w2-import');if(!raw){setError('No imported W-2 was found. Upload a W-2 first.');return;}const data=JSON.parse(raw) as Record<string,unknown>;setValues(Object.fromEntries(keys.map(([k])=>[k,String(data[k]??'')])) as unknown as W2);setFileName(sessionStorage.getItem('sfc:w2-file-name')||'');}catch{setError('Unable to read imported W-2. Please upload it again.')}},[]);
async function save(){const returnId=params.get('returnId')||sessionStorage.getItem('sfc:active-return-id');if(!returnId){setError('Select an active tax return before saving this W-2.');return;}if(!agreed){setError('Confirm the W-2 values first.');return;}setBusy(true);setError('');try{const response=await fetch('/api/tax/w2/confirm',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...values,returnId})});const body=await response.json();if(!response.ok||!body.success)throw new Error(body.error||'W-2 could not be saved');sessionStorage.removeItem('sfc:w2-import');sessionStorage.removeItem('sfc:w2-file-name');router.push('/tax-software/self-file/return?returnId='+encodeURIComponent(returnId));}catch(e){setError(e instanceof Error?e.message:'W-2 could not be saved')}finally{setBusy(false)}}
return <main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-4xl px-6 py-10"><p className="text-sm font-semibold text-sky-700">PARIS / Income</p><h1 className="mt-2 text-3xl font-bold">Review imported W-2</h1><p className="mt-3 text-slate-600">Verify each value against your original document before saving it to the return.</p>{fileName&&<p className="mt-3 text-sm">Imported file: <strong>{fileName}</strong></p>}<div className="mt-8 rounded-2xl border bg-white p-6"><div className="grid gap-4 sm:grid-cols-2">{keys.map(([key,label])=><label key={key} className="block"><span className="text-sm font-semibold">{label}</span><input className="mt-1 w-full rounded-lg border px-3 py-2" value={values[key]} onChange={e=>{setAgreed(false);setValues(v=>({...v,[key]:e.target.value}))}}/></label>)}</div><label className="mt-6 flex gap-3"><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)}/><span>I compared the extracted information with my original W-2 and confirm it is accurate.</span></label>{error&&<p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}<button type="button" onClick={save} disabled={busy||!agreed} className="mt-6 rounded-xl bg-sky-700 px-6 py-3 font-semibold text-white disabled:opacity-50">{busy?'Saving…':'Save confirmed W-2 to return'}</button></div></div></main>}

export default function W2ConfirmPage(){return <Suspense fallback={<p role="status">Loading W-2 confirmation…</p>}><W2ConfirmContent/></Suspense>}
