-- RLS policies for tax source-data tables used by self-file and professional return preparation.
create index if not exists idx_tax_w2_return on public.tax_w2_income(tax_return_id);
create index if not exists idx_tax_1099_return on public.tax_1099_income(tax_return_id);
create index if not exists idx_tax_schedule_c_return on public.tax_schedule_c(tax_return_id);
create index if not exists idx_tax_itemized_return on public.tax_itemized_deductions(tax_return_id);
create policy "tax_w2_staff_access" on public.tax_w2_income for all to authenticated using(exists(select 1 from public.tax_returns r where r.id=tax_w2_income.tax_return_id and (r.user_id=(select auth.uid()) or exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role in ('admin','super_admin','tax_preparer'))))) with check(exists(select 1 from public.tax_returns r where r.id=tax_w2_income.tax_return_id and (r.user_id=(select auth.uid()) or exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role in ('admin','super_admin','tax_preparer')))));
create policy "tax_1099_staff_access" on public.tax_1099_income for all to authenticated using(exists(select 1 from public.tax_returns r where r.id=tax_1099_income.tax_return_id and (r.user_id=(select auth.uid()) or exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role in ('admin','super_admin','tax_preparer'))))) with check(exists(select 1 from public.tax_returns r where r.id=tax_1099_income.tax_return_id and (r.user_id=(select auth.uid()) or exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role in ('admin','super_admin','tax_preparer')))));
create policy "tax_schedule_c_staff_access" on public.tax_schedule_c for all to authenticated using(exists(select 1 from public.tax_returns r where r.id=tax_schedule_c.tax_return_id and (r.user_id=(select auth.uid()) or exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role in ('admin','super_admin','tax_preparer'))))) with check(exists(select 1 from public.tax_returns r where r.id=tax_schedule_c.tax_return_id and (r.user_id=(select auth.uid()) or exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role in ('admin','super_admin','tax_preparer')))));
create policy "tax_itemized_staff_access" on public.tax_itemized_deductions for all to authenticated using(exists(select 1 from public.tax_returns r where r.id=tax_itemized_deductions.tax_return_id and (r.user_id=(select auth.uid()) or exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role in ('admin','super_admin','tax_preparer'))))) with check(exists(select 1 from public.tax_returns r where r.id=tax_itemized_deductions.tax_return_id and (r.user_id=(select auth.uid()) or exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role in ('admin','super_admin','tax_preparer')))));
